excel:
  file_path: "excel.xlsx"
  columns:
    - "ID"
    - "Name"
api:
  ms_endpoint: "https://www.endpoint.com?dataid=<ID>&typeId=1&testName=<Name>&interfaceId=3"
  aem_endpoint: "http://localhost:4502/bin/create-article.json"